#pragma once

#include <scetypes.h>

#define PSVS_CLOCK_MAGIC	(0x4000)
#define PSVS_500_MHZ_KEY	(65536)

typedef enum {
	PSVS_LOCK_DEVICE_NONE = 0,
	PSVS_LOCK_DEVICE_CPU = 1,
	PSVS_LOCK_DEVICE_GPU_ES4 = 2,
	PSVS_LOCK_DEVICE_BUS = 4,
	PSVS_LOCK_DEVICE_GPU_XBAR = 8,
	/*PSVS_LOCK_DEVICE_VENEZIA = 16,
	PSVS_LOCK_DEVICE_DMAC5 = 32,
	PSVS_LOCK_DEVICE_COMPAT = 64,
	PSVS_LOCK_DEVICE_VIP = 128,
	PSVS_LOCK_DEVICE_SYS = 256,*/
	PSVS_LOCK_DEVICE_ALL = PSVS_LOCK_DEVICE_CPU | PSVS_LOCK_DEVICE_GPU_ES4 | PSVS_LOCK_DEVICE_BUS | PSVS_LOCK_DEVICE_GPU_XBAR
} PsvsLockDevice;

SceBool psvsClockFrequencyIsLockedProc(ScePID pid, PsvsLockDevice type);